### ISSUE TITLE
Handling of empty directories

### ISSUE THREAD

**Issue by jaegeral** [pacoorozco/dotfiles#4]
At the moment if you have an empty dir within the to be uploaded folder, the script stops with:
    2019/01/02 20:34:26 Error: Nothing to upload in ....

Not sure if it would make more sense to then go to the next directory.

Thoughts?

**Comment by pacoorozco** [comment]
The problem is that `gpup` are not giving different error codes when something fails. So, every time there is an error in `gpup` call my script ends. This is done in this way, because if `gpup` is erroring due to quota or internal server error, I don't want to miss this error. 

Possible solutions are:
1. Detect empty directories and skip them before calling `gpup`. 
1. When an error occurs in `gpup` print an error line and continue with the next directory. **This could be a problem when we are dealing with quotas in Google**
1. Do a PR in `gpup` to allow us to detect when this error is happening. 

What do you think?

**Comment by jaegeral** [comment]
Hm I think I would opt for option 1.
Because it would not cause additional API calls. But of course writing an error message to the user makes sense.
